version: 2
updates:
  - package-ecosystem: "npm"         
    directory: "/"                   # Location of package.json
    schedule:
      interval: "daily"             
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
    reviewers:
      - SanaIdrees03        
    allow:
      - dependency-type: "production"   # Follow versioning policy: only production deps
      - dependency-type: direct
      - dependency-type: indirect
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Skip breaking (major) changes
