version: 2
updates:
  - package-ecosystem: "npm"        # change to "pip", "maven", etc. as needed
    directory: "/"                  # directory that contains package.json or requirements.txt
    schedule:
      interval: "daily"             # check for updates daily (can be "weekly", "monthly")
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    reviewers:
      - your-github-username        # reviewer(s) to request review from
    # Optionally specify labels:
    labels:
      - "dependencies"
      - "automated"
