version: 2
updates:
  - package-ecosystem: "npm"         # Use "pip" for Python, "maven" for Java, etc.
    directory: "/"                   # Location of package.json or requirements.txt
    schedule:
      interval: "weekly"             # You can also set to "daily" if preferred
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
    reviewers:
      - your-github-username         # Replace with your actual GitHub username
    allow:
      - dependency-type: "production"   # Follow versioning policy: only production deps
      - dependency-type: direct
      - dependency-type: indirect
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Skip breaking (major) changes
