version: 2
updates:
  - package-ecosystem: "npm"         # Change to "pip" for Python, "maven" for Java
    directory: "/"                   # Location of package.json or requirements.txt
    schedule:
      interval: "daily"              # Check daily for updates
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    reviewers:
      - your-github-username         # Replace with your GitHub username
    allow:
      - dependency-type: "production"   # Follow versioning policy: only production deps
    ignore:
      - dependency-type: "development"  # Ignore dev dependencies
