name: Custom Workflow - Release Notes

# Trigger workflow on new tag creation
on:
  push:
    tags:
      - 'v*'  # triggers on tags like v1.0, v2.1, etc.

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Generate release notes
      - name: Generate release notes
        id: notes
        run: |
          echo "Generating release notes for tag $GITHUB_REF"
          echo "Release Notes for $GITHUB_REF" > release-notes.txt
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> release-notes.txt

      # Step 3: Optionally, create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
