name: Dependency Update Test

# Run on every PR to main (adjust branch name if needed)
on:
  pull_request:
    branches:
      - main

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    # only run the job when Dependabot opened the PR (saves CI minutes)
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # change as needed

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
