name: Scheduled Tasks

# Trigger on a schedule
on:
  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  # Optional: also allow manual trigger
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run a script or command
      - name: Run maintenance script
        run: |
          echo "Running scheduled maintenance..."
          # Example: backup data
          mkdir -p backup
          date > backup/backup_$(date +'%Y%m%d_%H%M%S').txt
          echo "Maintenance complete."

      # Step 3: Output logs
      - name: Show backup files
        run: ls -l backup
